service: iftthDEV # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs4.3
  region: eu-central-1

functions:
  startTimer:
    handler: handler.startTimer
    events:
      - http: POST start
  stopRunningTimer:
    handler: handler.stopRunningTimer
    events:
      - http: POST stop     
  cutToday:
    handler: handler.cutToday
    events:
      - http: POST cut